parameters:
- name: NA
  lower_bound: 10
  upper_bound: 40000
  values:
    - demes:
        A: 
          epochs:
            0: start_size 
- name: TA 
  upper_bound: 1000000
  lower_bound: 300000
  values:
    - demes:
        A: 
          epochs:
            0: end_time 
- name: NVIN
  lower_bound: 10
  upper_bound: 10000
  values:
    - demes:
        Vindija: 
          epochs:
            0: start_size 
- name: NMH
  lower_bound: 10
  upper_bound: 100000
  values:
    - demes:
        MH: 
          epochs:
            0: start_size 
            2: start_size 
- name: NB
  lower_bound: 10
  upper_bound: 40000
  values:
    - demes:
        MH: 
          epochs:
            1: start_size 
- name: TMH 
  upper_bound: 140000
  lower_bound: 80000
  values:
    - demes:
        MH: 
          epochs:
            2: end_time 
- name: NKHO0
  lower_bound: 10
  upper_bound: 40000
  values:
    - demes:
        KhomaniSan: 
          epochs:
            0: start_size 
- name: NKHO1
  lower_bound: 10
  upper_bound: 40000
  values:
    - demes:
        KhomaniSan: 
          epochs:
            1: start_size 
- name: NYOR0
  lower_bound: 10
  upper_bound: 40000
  values:
    - demes:
        Yoruba: 
          epochs:
            0: start_size 
- name: mKHOYOR
  lower_bound: 1e-8
  upper_bound: 1e-4
  values:
    - migrations:
        0: rate

constraints:
- params: [TA, TMH]
  constraint: greater_than