
log    = reports/job_$(Cluster).log
error  = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out
requirements    = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif

request_cpus   = 1
request_memory = 4GB
request_disk   = 4GB

executable = simulate_genome.sh      
arguments  = $(model) $(outfname)

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = \
    simulate_genome.py, \
    data.zip, \
    models/$(model)

queue model,outfname from sim_variables.txt
