log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out


requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = fit_model.sh
arguments = $(graph) subset_Bherer.pkl $(fout).yaml $(fout).csv


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    fit_model.py, \
    models/$(graph), \
    models/ghost_den_params_case0.yaml, \
    models/ghost_den_params_case1.yaml, \
    data/subset_Bherer.pkl


request_cpus = 1
request_memory = 500MB
request_disk = 1GB

queue graph,fout from grid_variables.txt