log = reports/job_$(Cluster)_$(Process).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out
requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = parse_buffers.sh      
arguments = $(chrom) $(mask)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    parse_buffers.py, \
    data/recombination_maps/Behrer/sexavg_chr$(chrom).txt.gz, \
    data/mutation_maps/roulette_b37_16bit/roulette_b37_chr$(chrom).npy.gz, \
    data/bed_files/filterbed_$(mask)/mask_chr$(chrom).bed.gz, \
    data/intervals/chromosome_arms/arms_chr$(chrom).txt, \
    data/vcf_files/merged/merged.variants.chr$(chrom).vcf.gz, \
    data/vcf_files/populations_sub


request_cpus = 1
request_memory = 8GB
request_disk = 2GB


queue mask,chrom from buffer_variables.txt
