
log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out

requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = run_pulse_LRT.sh      


arguments = $(rep) $(model)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = run_pulse_LRT.py, models


request_cpus = 1
request_memory = 4GB
request_disk = 2GB

queue model,rep from sim_vars.txt
