log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out


requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = fit_grid_model.sh
arguments = $(graph) $(model_set) $(data) $(fout).yaml $(fout).csv


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    scripts/fit_grid_model.py, \
    models/$(graph), \
    params, \
    data/$(data)


request_cpus = 1
request_memory = 500MB
request_disk = 1GB


queue graph,model_set,data,fout from scripts/variables.txt