log    = reports/job_$(Cluster).log
error  = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out

request_cpus    = 1
request_memory  = 300MB
request_disk    = 1GB
requirements    = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

executable = fit_model.sh
arguments  = $(graph_file) $(param_file) $(data_file) $(out_file)

transfer_input_files = \
    fit_model.py, \
    models/$(graph_file), \
    models/$(param_file), \
    simulated_data/$(data_file)

queue graph_file,param_file,data_file,out_file from fit_variables.txt
