log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out


requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = fit_AMH_N_null_model.sh    
arguments = $(Process)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    fit_AMH_N_null_model.py, \
    models/null.model.yaml, \
    models/null.params.yaml, \
    subset_stats.pkl


request_cpus = 1
request_memory = 500MB
request_disk = 1GB

queue 50