
import numpy as np
from dpluspy import parsing, bootstrapping


rule bootstrap:
    input:
        script = 'bootstrap.py',
        stats = expand('sums/sums_chr{chrom}.pkl', chrom=list(range(1, 23)))
    output:
        'African_stats_weighted.pkl'
    shell:
        """
        python {input.script} -i {input.stats} -o {output}
        """


rule parse:
    input:
        script = 'parse.py',
        vcf_file = '../../data/vcf_files/African/Africans.variants.chr{chrom}.vcf.gz',
        bed_file = '../../data/bed_files/strict_exons_1e-4M/mask_chr{chrom}.bed.gz',
        pop_file = '../../data/vcf_files/African/populations',
        map_file = '../../data/recombination_maps/Bherer_hg19/sexavg_chr{chrom}.txt.gz',
        mut_file = '../../data/mutation_maps/hg19/hg19_roulette_chr{chrom}.npy',
        regions_file = '../../data/windows/windows.chr{chrom}.txt',
        bins_file = 'bins25.txt'
    params:
        chrom = 'chr{chrom}'
    output:
        'sums/sums_chr{chrom}.pkl'
    shell:
        """
        python {input.script} \
            -vcf {input.vcf_file} \
            -pop {input.pop_file} \
            -bed {input.bed_file} \
            -map {input.map_file} \
            -mut {input.mut_file} \
            -bins {input.bins_file} \
            --regions {input.regions_file} \
            -chrom {params.chrom} \
            -o {output}
        """


