

configfile: "../config.yaml"
CHROMS = list(range(1, 23))


rule all:
    input:
        expand("merged/merged.variants.chr{chrom}.vcf.gz", chrom=CHROMS),


rule extract_sgdp_vcfs:
    # Extract desired VCFs from the SGDP tarball and their index files.
    input:
        config["sgdp_path"]
    output:
        vcf_file = "samples/sgdp/{sample}.annotated.nh2.variants.vcf.gz",
        index_file = "samples/sgdp/{sample}.annotated.nh2.variants.vcf.gz.tbi"
    params:
        vcf_file = "{sample}.annotated.nh2.variants.vcf.gz",
        index_file = "{sample}.annotated.nh2.variants.vcf.gz.tbi"
    shell:
        """
        tar -xvf {input} {params.vcf_file}
        mv {params.vcf_file} samples/sgdp
        tar -xvf {input} {params.index_file}
        mv {params.index_file} samples/sgdp
        """


rule split_and_reduce_sgdp_vcfs:
    # Split SGDP VCFs into respective chromosomes, and use bcftools annotate
    # to remove some fields that we don't require from them.
    input:
        vcf_file = "samples/sgdp/{sample}.annotated.nh2.variants.vcf.gz",
        index_file = "samples/sgdp/{sample}.annotated.nh2.variants.vcf.gz.tbi"
    output:
        "samples/sgdp/{sample}.variants.chr{chrom}.vcf.gz"
    params:
        chrom = "{chrom}"
    shell:
        """
        bcftools view -r {params.chrom} -Ou {input.vcf_file} | \
            bcftools annotate \
                -x ID,QUAL,INFO,FORMAT/PL,FORMAT/AD -o {output}
        """


rule index_split_and_reduced_sgdp_files:
    # These files must be indexed before merging.
    input:
        "samples/sgdp/{sample}.variants.chr{chrom}.vcf.gz"
    output:
        "samples/sgdp/{sample}.variants.chr{chrom}.vcf.gz.csi"
    shell:
        """
        bcftools index {input}
        """


rule index_merged_sgdp_vcfs:
    input:
        "sgdp/sgdp.merged.variants.chr{chrom}.vcf.gz"
    output:
        "sgdp/sgdp.merged.variants.chr{chrom}.vcf.gz.csi"
    shell:
        """
        bcftools index {input}
        """


rule extract_ancient_gvcf_variants:
    input:
        vcf_file = config["ancient_sample_dir"] + "{sample}/chr{chrom}_mq25_mapab100.vcf.gz",
        index_file = config["ancient_sample_dir"] + "{sample}/chr{chrom}_mq25_mapab100.vcf.gz"
    output:
        "samples/ancient/{sample}.variants.chr{chrom}.vcf.gz"
    shell:
        """
        bcftools view -c1 -Ou {input.vcf_file} | \
            bcftools annotate \
                -x QUAL,INFO,^FORMAT/GT,FORMAT/DP,FORMAT/GQ \
                -o {output}
        """


rule extract_chagyrskaya_gvcf_variants:
    input:
        vcf_file = config["ancient_sample_dir"] + "{sample}/chr{chrom}.noRB.vcf.gz",
        index_file = config["ancient_sample_dir"] + "{sample}/chr{chrom}.noRB.vcf.gz.csi"
    output:
        "samples/ancient/{sample}.variants.chr{chrom}.vcf.gz"
    shell:
        """
        bcftools view -c1 -Ou {input.vcf_file} | \
            bcftools annotate \
                -x QUAL,INFO,^FORMAT/GT,FORMAT/DP,FORMAT/GQ \
                -o {output}
        """


rule index_gvcf_variants:
    input:
        "samples/ancient/{sample}.variants.chr{chrom}.vcf.gz"
    output:
        "samples/ancient/{sample}.variants.chr{chrom}.vcf.gz.csi"
    shell:
        """
        bcftools index {input}
        """


rule merge_vcfs:
    input:
        ancient_vcfs = expand("samples/ancient/{sample}.variants.chr{{chrom}}.vcf.gz", 
            sample=config["ancient_samples"]),
        ancient_csis = expand("samples/ancient/{sample}.variants.chr{{chrom}}.vcf.gz.csi", 
                sample=config["ancient_samples"]),
        sgdp_vcfs = expand("samples/sgdp/{sample}.variants.chr{{chrom}}.vcf.gz",
                sample=config["sgdp_samples"]),
        sgdp_csis = expand("samples/sgdp/{sample}.variants.chr{{chrom}}.vcf.gz.csi", 
            sample=config["sgdp_samples"])
    output:
        "merged/merged.variants.chr{chrom}.vcf.gz"
    shell:
        """
        bcftools merge -0 {input.ancient_vcfs} {input.sgdp_vcfs} -Ou | \
            bcftools annotate -x ^FORMAT/GT -o {output} 
        """
