## downloads and unzips a number of recombination rate maps


CHROMS = list(range(1, 23))
PYRHO_POPS = ["YRI"]
OMNI_POPS = ["YRI"]


rule all:
    input:
        expand(
            "pyrho/hg19/{p}/{p}_recombination_map_hg19_chr_{c}.bed.gz",
            c=CHROMS, p=PYRHO_POPS
        ),
        expand(
            "pyrho/hg38/{p}/{p}_recombination_map_hg38_chr_{c}.bed.gz",
            c=CHROMS, p=PYRHO_POPS
        ),
        expand("deCODE/hg38/map_chr{c}.bed.gz", c=CHROMS),
        expand("omni/hg37/YRI/YRI-{c}_final.txt.gz", c=CHROMS)


rule download_pyrho_maps_hg19:
    output:
        "pyrho/hg_19_maps.tar"
    params:
        link = "https://zenodo.org/records/11437540/files/hg19_maps.tar.gz" 
    shell:
        """
        wget -P pyrho/ {params.link}
        gzip -d pyrho/hg19_maps.tar.gz
        """


rule unzip_pyrho_maps_hg19:
    input:
        "pyrho/hg_19_maps.tar"        
    output:
        expand(
            "pyrho/hg19/{{popul}}/{{popul}}_recombination_map_hg19_chr_{chrom}.bed.gz",
            chrom=CHROMS
        )
    shell:
        """
        tar -xf pyrho/hg19_maps.tar -C pyrho/ hg19/{wildcards.popul} 
        for x in pyrho/hg19/{wildcards.popul}/*;
            do gzip $x
        done
        """


rule download_pyrho_maps_hg38:
    output:
        "pyrho/hg_38_maps.tar"
    params:
        link = "https://zenodo.org/records/11437540/files/hg38_maps.tar.gz" 
    shell:
        """
        wget -P pyrho/ {params.link}
        gzip -d pyrho/hg38_maps.tar.gz
        """


rule unzip_pyrho_maps_hg38:
    input:
        "pyrho/hg_19_maps.tar"      
    output:
        expand(
            "pyrho/hg38/{{popul}}/{{popul}}_recombination_map_hg38_chr_{chrom}.bed.gz",
            chrom=CHROMS
        )
    shell:
        """
        tar -xf pyrho/hg38_maps.tar -C pyrho/ hg38/{wildcards.popul} 
        for x in pyrho/hg38/{wildcards.pop}/*;
            do gzip $x
        done
        """


rule download_omni_maps_hg37:
    ## from the phase 1 1kg data set
    output:
        expand("omni/hg37/YRI/YRI-{c}_final.txt.gz", c=CHROMS)
    params:
        link = (
            "https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/"
            "20130507_omni_recombination_rates/"
        ),
        suffix = "_omni_recombination_20130507.tar",
        pops = OMNI_POPS
    shell:
        """
        for pop in {params.pops}; do
            wget -P omni/hg37/ {params.link}$pop{params.suffix}
            tar -xf omni/hg37/${{pop}}{params.suffix} -C omni/hg37
        done
        """


rule download_decode_map:
    ## hg38. from Halldorsson et al 2019 sex average
    output:
        "deCODE/map_hg38.bed.gz"
    params:
        link = (
            "https://www.science.org/doi/suppl/10.1126/science.aau1043/"
            "suppl_file/aau1043_datas3.gz"
        )
    shell:
        """
        wget -O {output} {params.link}
        """

    
rule split_decode_map:
    input:
        "deCODE/map_hg38.bed.gz"
    output:
        "deCODE/hg38/map_chr{chrom}.bed.gz"
    shell:
        """
        zcat {input} | awk "/chr{wildcards.chrom}\t/" > {output}
        """