"""
downloads and prepares several recombination rate maps in genome build GRCh37 
"""


configfile: "../config.yaml"
CHROMS = list(range(1, 23))
PYRHO_POPULS = ["YRI", "CEU", "CHB"]
OMNI_POPULS = ["YRI", "CEU", "CHB"]


rule all:
    input:
        expand("Bherer/sexavg_chr{chrom}.txt.gz", chrom=CHROMS),
        expand("Zhou/{group}/{group}.chr{chrom}.1000.plinkmap.txt.gz", chrom=CHROMS, group=["FHS", "JHS"]), 
        expand("pyrho/{popul}/{popul}_recombination_map_hapmap_format_hg19_chr_{chrom}.txt.gz", chrom=CHROMS, popul=PYRHO_POPULS),
        expand("omni/{popul}/{popul}-{chrom}-final.txt.gz", chrom=CHROMS, popul=OMNI_POPULS)


rule download_bherer_map:
    output:
        "Refined_genetic_map_b37.tar.gz"
    params:
        link = "https://github.com/cbherer/Bherer_etal_SexualDimorphismRecombination/raw/refs/heads/master/Refined_genetic_map_b37.tar.gz"
    shell:
        """
        wget {params.link}
        """


rule extract_bherer_map:
    input:
        "Refined_genetic_map_b37.tar.gz"
    output:
        expand("Bherer/sexavg_chr{chrom}.txt", chrom=CHROMS),
        temporary(directory("Refined_genetic_map_b37/")), 
        temporary("Refined_genetic_map_b37.tar")
    shell:
        """
        gzip -d {input}
        tar -xf Refined_genetic_map_b37.tar
        mv Refined_genetic_map_b37/* Bherer/
        """


rule compress_bherer_map:
    input: 
        "Bherer/sexavg_chr{chrom}.txt"
    output:
        "Bherer/sexavg_chr{chrom}.txt.gz"
    shell:
        """ 
        gzip {input}
        """ 


rule download_zhou_maps:
    output:
        "{group}.map.tar.gz"
    params:
        link = "https://github.com/YingZhou001/IBDrecomb/raw/refs/heads/master/maps.b37/{group}.map.tar.gz"
    shell:
        """
        wget {params.link}
        """


rule extract_zhou_maps:
    input:
        "{group}.map.tar.gz"
    params: 
        tarball = "{group}.map.tar",
        folder = "{group}.map"
    output: 
        expand("Zhou_original/{{group}}.map/{{group}}.chr{chrom}.1000.plinkmap.gz", chrom=CHROMS),
        temporary("{group}.map.tar")
    shell:
        """ 
        gzip -d {input}
        tar -xf {params.tarball}
        mv {params.folder} Zhou_original/
        """


rule rearrange_zhou_maps:
    input:
        "Zhou_original/{group}.map/{group}.chr{chrom}.1000.plinkmap.gz"
    output:
        "Zhou/{group}/{group}.chr{chrom}.1000.plinkmap.txt"
    shell:
        """ 
        ( echo  "chrom Map(cM) Position(bp)";
        zcat {input} | tail -n +2 | cut -f4,3,1 -d " " ) > {output}
        """


rule compress_zhou_maps:
    input: 
        "Zhou/{group}/{group}.chr{chrom}.1000.plinkmap.txt"
    output:
        "Zhou/{group}/{group}.chr{chrom}.1000.plinkmap.txt.gz"
    shell:
        """ 
        gzip {input}
        """ 


rule copy_pyrho_archive:
    input:
        config["pyrho_path"]
    output:
        "hg19_maps.tar.gz"
    shell:
        """
        cp {input} {output}
        """


rule ungzip_pyrho_archive:
    input:
        "hg19_maps.tar.gz"
    output:
        temporary("hg19_maps.tar")
    shell:
        """
        gzip -d {input}
        """


rule extract_pyrho_maps:
    input:
        "hg19_maps.tar"  
    output:
        "hg19/{popul}/{popul}_recombination_map_hapmap_format_hg19_chr_{chrom}.txt"
    shell:
        """
        tar -xf {input} {output}
        """


rule rename_pyrho_dir:
    input:
        expand("hg19/{popul}/{popul}_recombination_map_hapmap_format_hg19_chr_{chrom}.txt", popul=PYRHO_POPULS, chrom=CHROMS)
    output:
        expand("pyrho/{popul}/{popul}_recombination_map_hapmap_format_hg19_chr_{chrom}.txt", popul=PYRHO_POPULS, chrom=CHROMS)
    shell:
        """
        mv hg19/* pyrho
        rm -r hg19
        """


rule compress_pyrho_maps:
    input: 
        "pyrho/{popul}/{popul}_recombination_map_hapmap_format_hg19_chr_{chrom}.txt"
    output:
        "pyrho/{popul}/{popul}_recombination_map_hapmap_format_hg19_chr_{chrom}.txt.gz"
    shell:
        """ 
        gzip {input}
        """ 


rule download_omni_map:
    params: 
        link = "https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/20130507_omni_recombination_rates/{popul}_omni_recombination_20130507.tar"
    output:
        temporary("{popul}_omni_recombination_20130507.tar")
    shell:
        """
        wget {params.link}
        """


rule extract_omni_map:
    input: 
        "{popul}_omni_recombination_20130507.tar"
    output:
        expand("omni/{{popul}}/{{popul}}-{chrom}-final.txt.gz", chrom=CHROMS)
    shell:
        """
        tar -xf {input} -C omni/
        """
