log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out


requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = fit_model.sh
arguments = $(graph_file) $(param_file) $(data_file) $(out_file)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    fit_model.py, \
    $(graph_file), \
    $(param_file), \
    ../data/$(data_file)


request_cpus = 1
request_memory = 400MB
request_disk = 1GB

queue graph_file,param_file,data_file,out_file from variables.txt