log = reports/job_$(Cluster)_$(Process).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out

requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = parse_with_map.sh      


arguments = $(chrom) $(map_name) $(map_file) $(pos_col) $(map_col)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    parse_with_map.py, \
    data/recombination_maps/$(map_name)/$(map_file), \
    data/mutation_maps/roulette_b37_16bit/roulette_b37_chr$(chrom).npy.gz, \
    data/bed_files/filterbed_1e-4M_exon_buffer/mask_chr$(chrom).bed.gz, \
    data/intervals/1e-4_exon_buffer_1.3Mb/intervals_chr$(chrom).txt, \
    data/vcf_files/merged/merged.variants.chr$(chrom).vcf.gz, \
    data/vcf_files/populations


request_cpus = 1
request_memory = 8GB
request_disk = 4GB

queue chrom,map_name,map_file,pos_col,map_col from variables
