
log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out

requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = one_epoch_model.sh      


arguments = $(Process)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = one_epoch_model.py, models


request_cpus = 1
request_memory = 4GB
request_disk = 2GB

queue 100
