

CHROMS = [1]
BINS = [0, 1, 2, 3, 4]


rule all:
    input:
        expand("Africans_Behrer_bin{b}_chr{chrom}.pkl", b=BINS, chrom=CHROMS),
        expand("Africans_Behrer_not_binned_chr{chrom}.pkl", chrom=CHROMS)


rule parse_h2_nobins:
    input:
        vcf_file = "../../data/genotypes/sets/Africans/vcf_files/SGDP_Africans_chr{chrom}.vcf.gz",
        bed_file = "../../data/genotypes/sets/Africans/bed_files/base/SGDP_Africans_chr{chrom}.bed.gz",
        mut_file = "../../data/mutation_maps/h37/mut_maps/mut_map_h37_chr{chrom}.npy",
        rec_file = "../../data/recombination_maps/Bherer/Refined_genetic_map_b37/sexavg_chr{chrom}.txt.gz",
        region_file = "../../data/misc/arms/arms_{chrom}.txt",
        bins = "log_bins_17.txt",
        pop_file = "populations"
    output:
        "stats/stats_no_bins_chr{chrom}.pkl"
    shell:
        """
        parse_h2 \
            -v {input.vcf_file} \
            -b {input.bed_file} \
            -r {input.rec_file} \
            -m {input.mut_file} \
            -R {input.region_file} \
            --r_bins {input.bins} \
            --chrom_num {wildcards.chrom} \
            --compute_two_pop \
            --compute_denoms \
            -p {input.pop_file} \
            -o {output}
        """


rule parse_h2:
    input:
        vcf_file = "../../data/genotypes/sets/Africans/vcf_files/SGDP_Africans_chr{chrom}.vcf.gz",
        bed_file = "mask_bin{b}_chr{chrom}.bed.gz",
        mut_file = "../../data/mutation_maps/h37/mut_maps/mut_map_h37_chr{chrom}.npy",
        rec_file = "../../data/recombination_maps/Bherer/Refined_genetic_map_b37/sexavg_chr{chrom}.txt.gz",
        region_file = "../../data/misc/arms/arms_{chrom}.txt",
        bins = "log_bins_17.txt",
        pop_file = "populations"
    output:
        "stats/stats_bin{b}_chr{chrom}.pkl"
    shell:
        """
        parse_h2 \
            -v {input.vcf_file} \
            -b {input.bed_file} \
            -r {input.rec_file} \
            -m {input.mut_file} \
            -R {input.region_file} \
            --r_bins {input.bins} \
            --chrom_num {wildcards.chrom} \
            --compute_two_pop \
            --compute_denoms \
            -p {input.pop_file} \
            -o {output}
        """


rule bootstrap:
    input:
        expand("stats/stats_bin{{b}}_chr{chrom}.pkl", chrom=CHROMS)
    output:
        "Africans_Behrer_bin{b}_chr{chrom}.pkl"
    shell:
        """
        bootstrap_h2 -i {input} -o {output} --weighted --num_reps 1000
        """


rule bootstrap_no_bins:
    input:
        expand( "stats/stats_no_bins_chr{chrom}.pkl", chrom=CHROMS)
    output:
        "Africans_Behrer_not_binned_chr{chrom}.pkl"
    shell:
        """
        bootstrap_h2 -i {input} -o {output} --weighted --num_reps 1000
        """
       