log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out


requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = fit_model.sh
arguments = \
    deep_struc_subset_model.yaml \
    deep_struc_subset_model_params_TKho.yaml \
    subset_Bherer.pkl \
    deep_struc_subset_model_free_TKho_fit_$(Process).yaml
    


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    fit_model.py, \
    deep_struc_subset_model_params_TKho.yaml, \
    deep_struc_subset_model.yaml, \
    ../data/subset_Bherer.pkl


request_cpus = 1
request_memory = 250MB
request_disk = 1GB

queue 10