log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out


requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = fit_model.sh
arguments = basal_eur_model.yaml \
    basal_eur_model_params.yaml \
    subset_Bherer.pkl \
    basal_eur_fit$(Process).yaml \
    basal_eur_fit$(Process).csv


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    fit_model.py, \
    models/basal_eur_model.yaml, \
    models/basal_eur_model_params.yaml, \
    data/subset_Bherer.pkl


request_cpus = 1
request_memory = 500MB
request_disk = 1GB

queue 10