log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out


requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = fit_to_bootstrap_sample.sh
arguments = $(graph_file) $(param_file) $(data_file) $(sample) $(out_file)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    fit_to_bootstrap_sample.py, \
    models/$(graph_file), \
    models/$(param_file), \
    ../../data/$(data_file)


request_cpus = 1
request_memory = 400MB
request_disk = 1GB


queue graph_file,param_file,data_file,sample,out_file from variables.txt