##invoke the fit_H2 script
# created 2024-10-11
# edited 15-01-2025

## --- variables: edit here --- ##

graph = tree_three_pulse.yaml
params = params_three_pulse.yaml
out = three_pulse_$(Cluster)-$(Process).yaml
data = Behrer10kb.pkl
u = 1.1e-8

maxiter = 10000
perturb = 0.3
method = NelderMead
reps = 30

## --- end variables --- ## 

log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out

requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/h2py-container.sif

executable = fit_h2.sh      

arguments = \
 -d $(data) \
 -g $(graph) \
 -p $(params) \
 -o $(out) \
 -u $(u) \
 --perturb $(perturb) \
 --max_iter $(maxiter) \
 --method $(method) \
 --verbose 10 \
 --include_H 0 \

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = \
 ../data/statistics/$(data), \
 ../models/$(graph), \
 ../models/$(params)

request_cpus = 1
request_memory = 500MB
request_disk = 800MB

queue $(reps)
