"""
Constructs genetic masks.
"""


configfile: "../config.yaml"
CHROMS = list(range(1, 23))


rule all:
    input:
        expand("intergenic/mask_chr{chrom}.bed.gz", chrom=CHROMS),
        expand("10kb_buffer/mask_chr{chrom}.bed.gz", chrom=CHROMS),
        expand("50kb_buffer/mask_chr{chrom}.bed.gz", chrom=CHROMS),
        expand("1e-4M_buffer/mask_chr{chrom}.bed.gz", chrom=CHROMS),
        expand("1e-4M_buffer_strict/mask_chr{chrom}.bed.gz", chrom=CHROMS)


rule download_ccds_exon_tables:
    input:
        "download_ccds_exons.R"
    output:
        expand("ccds_exons/exons_chr{chrom}.bed", chrom=CHROMS)
    shell:
        """
        Rscript {input}
        """


rule download_1kg_combined_mask:
    output:
        temporary("20140520.combined_mask.autosomes.bed")
    params:
        link = "https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/accessible_genome_masks/20140520.combined_mask.autosomes.bed"
    shell:
        """
        wget {params.link}
        """


rule split_1kg_combined_mask:
    # Break the 1KG mask up by chromosome
    input:
        "20140520.combined_mask.autosomes.bed"
    output:
        "1KG_combined/mask_chr{chrom}.bed"
    params:
        chrom_num = "chr{chrom}"
    shell:
        """ 
        awk '$1=="{params.chrom_num}"' {input} > {output}
        """


rule download_1kg_strict_mask:
    output:
        temporary("20140520.strict_mask.autosomes.bed")
    params:
        link = "https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/accessible_genome_masks/20140520.strict_mask.autosomes.bed"
    shell:
        """
        wget {params.link}
        """


rule split_1kg_strict_mask:
    # Break the 1KG mask up by chromosome
    input:
        "20140520.strict_mask.autosomes.bed"
    output:
        "1KG_strict/mask_chr{chrom}.bed"
    params:
        chrom_num = "chr{chrom}"
    shell:
        """
        awk '$1=="{params.chrom_num}"' {input} > {output}
        """


rule build_roulette_masks:
    # Build masks denoting coverage of the Roulette mutation maps
    input: 
        script = "../../tools/make_map_coverage_bed_file.py",
        npy_file = "../mutation_maps/roulette/map_chr{chrom}.npy"
    output:
        "roulette_coverage/mask_chr{chrom}.bed.gz"
    params:
        chrom_num = "chr{chrom}"
    shell:
        """
        python {input.script} \
            -i {input.npy_file} \
            --chrom_num {params.chrom_num} \
            -o {output}
        """
    

rule intersect_masks:
    # Merge callability filters for ancient genomes, the 1KG strict mask, and the Roulette mutation map coverage.
    input:
        script = "../../tools/intersect_bed_files.py",
        filterbeds = expand(config["filterbed_dir"] + "{sample}/chr{{chrom}}_mask.bed.gz", sample=config["ancient_samples"]),
        combined_mask = "1KG_combined/mask_chr{chrom}.bed",
        roulette_mask = "roulette_coverage/mask_chr{chrom}.bed.gz"
    output:
        "basis/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.filterbeds} {input.combined_mask} {input.roulette_mask} \
            -o {output}
        """


rule make_intergenic_mask:
    input:
        script = "../../tools/subtract_bed_files.py",
        basis = "basis/mask_chr{chrom}.bed.gz",
        exons = "ccds_exons/exons_chr{chrom}.bed"
    output:
        "intergenic/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.basis} \
            -i2 {input.exons} \
            -o {output}
        """


rule slop_exons_10kb:
    input:
        script = "../../tools/slop_bed_file.py",
        exons = "ccds_exons/exons_chr{chrom}.bed"
    params:
        buffer = "10000"
    output:
        "buffers/10kb/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.exons} \
            --buffer {params.buffer} \
            -o {output}
        """


rule slop_exons_50kb:
    input:
        script = "../../tools/slop_bed_file.py",
        exons = "ccds_exons/exons_chr{chrom}.bed"
    params:
        buffer = "50000"
    output:
        "buffers/50kb/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.exons} \
            --buffer {params.buffer} \
            -o {output}
        """


rule slop_exons_1e_4M:
    input:
        script = "../../tools/slop_bed_file_with_map.py",
        exons = "ccds_exons/exons_chr{chrom}.bed",
        map_file = "../recombination_maps/Bherer/sexavg_chr{chrom}.txt.gz"
    params:
        buffer = "1e-4"
    output:
        "buffers/1e-4M/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.exons} \
            -r {input.map_file} \
            --buffer {params.buffer} \
            -o {output}
        """


rule subtract_exons_10kb:
    input:
        script = "../../tools/subtract_bed_files.py",
        basis = "basis/mask_chr{chrom}.bed.gz",
        exons_buffers = "buffers/10kb/mask_chr{chrom}.bed.gz"
    output:
        "10kb_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.basis} \
            -i2 {input.exons_buffers} \
            -o {output}
        """


rule subtract_exons_50kb:
    input:
        script = "../../tools/subtract_bed_files.py",
        basis = "basis/mask_chr{chrom}.bed.gz",
        exons_buffers = "buffers/50kb/mask_chr{chrom}.bed.gz"
    output:
        "50kb_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.basis} \
            -i2 {input.exons_buffers} \
            -o {output}
        """


rule subtract_exons_1e_4M:
    input:
        script = "../../tools/subtract_bed_files.py",
        basis = "basis/mask_chr{chrom}.bed.gz",
        exons_buffers = "buffers/1e-4M/mask_chr{chrom}.bed.gz"
    output:
        "1e-4M_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.basis} \
            -i2 {input.exons_buffers} \
            -o {output}
        """


rule build_strict_mask_1e_4M:
    # use the strict 1KG mask on top of the 1e-4M CCDS exon-buffer map
    input:
        script = "../../tools/intersect_bed_files.py",
        base = "1e-4M_buffer/mask_chr{chrom}.bed.gz",
        strict_mask = "1KG_strict/mask_chr{chrom}.bed",
    output:
        "1e-4M_buffer_strict/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.base} {input.strict_mask} \
            -o {output}
        """




