"""
Construct genetic masks.
"""


configfile: "../config.yaml"


CHROMS = list(range(1, 23))


rule all:
    input:
        expand("filterbed_intergenic/mask_chr{chrom}.bed.gz", chrom=CHROMS),
        expand("filterbed_10kb_exon_buffer/mask_chr{chrom}.bed.gz", chrom=CHROMS),
        expand("filterbed_20kb_exon_buffer/mask_chr{chrom}.bed.gz", chrom=CHROMS),
        expand("filterbed_50kb_exon_buffer/mask_chr{chrom}.bed.gz", chrom=CHROMS),
        expand("filterbed_1e-4M_exon_buffer/mask_chr{chrom}.bed.gz", chrom=CHROMS),


rule merge_filterbed:
    # Merge callability filters for ancient genomes and the 1KG strict mask
    input:
        script = "../../tools/bedfile_intersect.py",
        filter_beds = expand("raw/filterbed/{sample}/chr{{chrom}}_mask.bed.gz", 
            sample=config["ancient_samples"]),
        strict_bed = "raw/phase3_strict_mask/strict_chr{chrom}.bed.gz"
    output:
        "filterbed/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.filter_beds} {input.strict_bed} \
            -o {output}
        """


rule merge_filterbed_and_roulette:
    # Merge merged filterbed mask with Roulette mutation map coverage mask
    input:
        script = "../../tools/bedfile_intersect.py",
        filter_bed = "filterbed/mask_chr{chrom}.bed.gz",
        roulette_bed = "raw/roulette_hg19_coverage/mask_chr{chrom}.bed.gz"
    output:
        "filterbed_roulette/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.filter_bed} {input.roulette_bed} \
            -o {output}
        """


rule subtract_exons:
    # Remove exonic intervals from the filterbed/strict/roulette mask
    input:
        script = "../../tools/bedfile_difference.py",
        filter_bed = "filterbed_roulette/mask_chr{chrom}.bed.gz",
        exon_bed = "raw/exons_hg19/{chrom}_exons.bed.gz"
    output:
        "filterbed_intergenic/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.filter_bed} \
            -i2 {input.exon_bed} \
            -o {output}
        """


rule slop_exons_10kb:
    input:
        script = "../../tools/bedfile_slop.py",
        bed_file = "raw/exons_hg19/{chrom}_exons.bed.gz"
    params:
        buffer = "10000"
    output:
        "buffers/exons_10kb_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.bed_file} \
            --buffer {params.buffer} \
            -o {output}
        """


rule slop_exons_20kb:
    input:
        script = "../../tools/bedfile_slop.py",
        bed_file = "raw/exons_hg19/{chrom}_exons.bed.gz"
    params:
        buffer = "20000"
    output:
        "buffers/exons_20kb_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.bed_file} \
            --buffer {params.buffer} \
            -o {output}
        """


rule slop_exons_50kb:
    input:
        script = "../../tools/bedfile_slop.py",
        bed_file = "raw/exons_hg19/{chrom}_exons.bed.gz"
    params:
        buffer = "50000"
    output:
        "buffers/exons_50kb_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.bed_file} \
            --buffer {params.buffer} \
            -o {output}
        """


rule subtract_exons_10kb:
    input:
        script = "../../tools/bedfile_difference.py",
        filter_bed = "filterbed_roulette/mask_chr{chrom}.bed.gz",
        buffer_bed = "buffers/exons_10kb_buffer/mask_chr{chrom}.bed.gz"
    output:
        "filterbed_10kb_exon_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.filter_bed} \
            -i2 {input.buffer_bed} \
            -o {output}
        """


rule subtract_exons_20kb:
    input:
        script = "../../tools/bedfile_difference.py",
        filter_bed = "filterbed_roulette/mask_chr{chrom}.bed.gz",
        buffer_bed = "buffers/exons_20kb_buffer/mask_chr{chrom}.bed.gz"
    output:
        "filterbed_20kb_exon_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.filter_bed} \
            -i2 {input.buffer_bed} \
            -o {output}
        """


rule subtract_exons_50kb:
    input:
        script = "../../tools/bedfile_difference.py",
        filter_bed = "filterbed_roulette/mask_chr{chrom}.bed.gz",
        buffer_bed = "buffers/exons_50kb_buffer/mask_chr{chrom}.bed.gz"
    output:
        "filterbed_50kb_exon_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.filter_bed} \
            -i2 {input.buffer_bed} \
            -o {output}
        """


rule slop_exons_1_4M:
    input:
        script = "../../tools/bedfile_rslop.py",
        bed_file = "raw/exons_hg19/{chrom}_exons.bed.gz",
        map_file = "../recombination_maps/Bherer_b37/sexavg_chr{chrom}.txt"
    params:
        distance = "1e-4"
    output:
        "buffers/exons_1e-4M_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i {input.bed_file} \
            -r {input.map_file} \
            --buffer {params.distance} \
            -o {output}
        """


rule subtract_exons_1_4M:
    input:
        script = "../../tools/bedfile_difference.py",
        filter_bed = "filterbed_roulette/mask_chr{chrom}.bed.gz",
        buffer_bed = "buffers/exons_1e-4M_buffer/mask_chr{chrom}.bed.gz"
    output:
        "filterbed_1e-4M_exon_buffer/mask_chr{chrom}.bed.gz"
    shell:
        """
        python {input.script} \
            -i1 {input.filter_bed} \
            -i2 {input.buffer_bed} \
            -o {output}
        """

