log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out


requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif


executable = fit_null_model.sh
arguments = ghost_den_null_model.yaml \
    ghost_den_null_model_params.yaml \
    subset_Bherer.pkl \
    ghost_den_fit_null_$(Process).yaml \ 
    ghost_den_fit_null_$(Process).csv


should_transfer_files = YES
when_to_transfer_output = ON_EXIT


transfer_input_files = \
    fit_null_model.py, \
    models/ghost_den_null_model.yaml, \
    models/ghost_den_null_model_params.yaml, \
    data/subset_Bherer.pkl


request_cpus = 1
request_memory = 500MB
request_disk = 1GB

queue 10