log = reports/job_$(Cluster)_$(Process).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out

requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/dpluspy-container.sif

executable = parse_dplus.sh      

arguments = $(chrom) $(map_name) $(map_file) $(pos_col) $(map_col)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = \
    parse_dplus.py, \
    data/recombination_maps/$(map_name)/$(map_file), \
    data/mutation_maps/roulette_1kb_chr$(chrom).csv.gz, \
    data/masks/mask_chr$(chrom).bed.gz, \
    data/windows/windows.chr$(chrom).txt, \
    data/vcf_files/Eurasians.variants.chr$(chrom).vcf.gz, \
    data/vcf_files/populations

request_cpus = 1
request_memory = 4GB
request_disk = 2GB

queue chrom,map_name,map_file,pos_col,map_col from variables
